import { Service, Testimonial, Vehicle, VehicleType } from './types';

export const FLEET_DATA: Vehicle[] = [
  {
    id: '1',
    name: 'Swift Dzire',
    type: VehicleType.ANY_SEDAN,
    capacity: 4,
    luggage: 2,
    pricePerHour: 14,
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=800',
    features: ['AC', 'Music System', 'Professional Driver'],
    available: true,
  },
  {
    id: '2',
    name: 'Toyota Camry',
    type: VehicleType.SEDAN,
    capacity: 4,
    luggage: 3,
    pricePerHour: 18,
    image: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&q=80&w=800',
    features: ['Premium Interior', 'Extra Legroom', 'USB Charging'],
    available: true,
  },
  {
    id: '3',
    name: 'Maruti Ertiga',
    type: VehicleType.ANY_SUV,
    capacity: 6,
    luggage: 3,
    pricePerHour: 22,
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=800',
    features: ['AC', 'Spacious Seating', 'Carrier Included'],
    available: true,
  },
  {
    id: '4',
    name: 'Innova/Crysta',
    type: VehicleType.INNOVA,
    capacity: 7,
    luggage: 4,
    pricePerHour: 28,
    image: 'https://images.unsplash.com/photo-1625332866504-2d5757d54942?auto=format&fit=crop&q=80&w=800',
    features: ['Luxury Captain Seats', 'Dual AC', 'Pushback Seats'],
    available: true,
  },
  {
    id: '5',
    name: 'Tempo Traveller',
    type: VehicleType.TEMPO_TRAVELLER,
    capacity: 12,
    luggage: 10,
    pricePerHour: 45,
    image: 'https://images.unsplash.com/photo-1527786356703-4b100091cd2c?auto=format&fit=crop&q=80&w=800',
    features: ['High Roof', 'Pushback Seats', 'Audio/Video System'],
    available: true,
  },
  {
    id: '6',
    name: 'Force Urbania',
    type: VehicleType.URBANIA,
    capacity: 13,
    luggage: 8,
    pricePerHour: 65,
    image: 'https://images.unsplash.com/photo-1517524285303-d6fc683dddf8?auto=format&fit=crop&q=80&w=800',
    features: ['Luxury Cabin', 'Individual AC', 'European Safety'],
    available: true,
  },
  {
    id: '7',
    name: 'Tourist Bus',
    type: VehicleType.TOURIST_BUS,
    capacity: 40,
    luggage: 50,
    pricePerHour: 120,
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&q=80&w=800',
    features: ['AC/Non-AC Options', 'Tour Guide Mic', 'Large Boot Space'],
    available: true,
  }
];

export const SERVICES_DATA: Service[] = [
  {
    id: '1',
    title: 'Airport Transfers',
    description: 'Fast airport drops to CJB and major hubs.',
    icon: 'plane',
  },
  {
    id: '2',
    title: 'Hourly Rental',
    description: 'Flexible city packages for business & shopping.',
    icon: 'clock',
  },
  {
    id: '3',
    title: 'Outstation Trips',
    description: 'Safe long-distance rides from Coimbatore.',
    icon: 'map-pin',
  },
  {
    id: '4',
    title: 'Corporate Travel',
    description: 'Premium mobility for Coimbatore businesses.',
    icon: 'briefcase',
  },
];

export const TESTIMONIALS_DATA: Testimonial[] = [
  { id: '1', name: 'Arun Kumar', role: 'Airport Transfer', rating: 5, comment: 'Early morning pickup semma quick, Coimbatore airport-ku safe-aa drop pannanga. Very professional service.' },
  { id: '2', name: 'Priya M', role: 'Outstation Trip', rating: 5, comment: 'Coimbatore to Kodaikanal trip super comfortable. Driver polite-ah irundhaaru. Car clean & AC cool.' },
  { id: '3', name: 'Sathish Raj', role: 'Outstation', rating: 4, comment: 'Ooty trip smooth-aa pochu. Speed control super, safety maintained throughout.' },
  { id: '4', name: 'Meena Devi', role: 'Rental (Day Hire)', rating: 5, comment: 'Full day rental eduthom, driver patience aa irundhaar. Amma appa comfortable-aa travel pannanga.' },
  { id: '5', name: 'Vignesh S', role: 'City to City', rating: 5, comment: 'Coimbatore to Chennai ride very smooth. Time maintain pannanga, zero tension.' },
  { id: '6', name: 'Naveen Kumar', role: 'Airport Transfer', rating: 4, comment: 'Airport pickup on time, luggage help pannanga. Good service but AC konjam strong irundhudhu.' },
  { id: '7', name: 'Ramya Shree', role: 'Outstation Drop', rating: 5, comment: 'Family function-ku Madurai ponom. Driver friendly & safe. Romba thanks.' },
  { id: '8', name: 'Stephen Joseph', role: 'Outstation', rating: 5, comment: 'Valparai roads-la careful drive pannaaru. Enjoyable trip without any risk.' },
  { id: '9', name: 'Gokul Pranav', role: 'Rental (Day Hire)', rating: 4, comment: 'Car neat-a irundhudhu. Rate reasonable. Next time kooda book panren.' },
  { id: '10', name: 'Divya K', role: 'City to City', rating: 5, comment: 'Coimbatore to Kochi travel semma smooth. Driver route perfect-a theriyum.' },
  { id: '11', name: 'Harish R', role: 'Airport Transfer', rating: 5, comment: 'Late night flight irundhadhu, still punctual pickup. Ladies travel safe.' },
  { id: '12', name: 'Ishwarya P', role: 'One-Way Outstation', rating: 4, comment: 'Salem drop comfortable. Traffic avoid panni quick reach pannanga.' },
  { id: ' balaji', name: 'Balaji', role: 'Outstation', rating: 5, comment: 'Kodai trip la music calm-a vechirundhaar. Family enjoy pannom.' },
  { id: '14', name: 'Farhana F', role: 'Rental (Day Hire)', rating: 5, comment: 'Temple visits full day schedule perfect follow pannanga. 100% satisfied.' },
  { id: '15', name: 'Nithin A', role: 'City to City', rating: 5, comment: 'Erode-ku urgent office meeting. Driver time save pannaaru. Great service.' },
  { id: '16', name: 'Keerthana', role: 'Airport Transfer', rating: 4, comment: 'Flight miss aagama help panni drop pannanga. Super support.' },
  { id: '17', name: 'Sanjay R', role: 'Outstation Trip', rating: 5, comment: 'College trip-ku Palani ponom. Rate student friendly. Recommend pannuren.' },
  { id: '18', name: 'Madhumitha', role: 'Outstation', rating: 5, comment: 'Munnar-la potholes irundhaalum smooth driving. Zero fear.' },
  { id: '19', name: 'Aravind V', role: 'Rental (Day Hire)', rating: 4, comment: 'Business meetings full day. Driver professional aa wait pannaaru.' },
  { id: '20', name: 'Sandhya L', role: 'City to City', rating: 5, comment: 'CBE to Madurai ride stress free. Elder passengers comfortable.' },
  { id: '21', name: 'Lokesh', role: 'Airport Transfer', rating: 5, comment: 'Baby seat request instant arrange pannanga. Very responsible service.' },
  { id: '22', name: 'Rekha S', role: 'One-Way Outstation', rating: 4, comment: 'Pondicherry drop-ku help pannaaru. Nice driver.' },
  { id: '23', name: 'Karunakaran', role: 'Outstation', rating: 5, comment: 'Mysore trip cost worth every rupee. No hidden charges.' },
  { id: '24', name: 'Jennifer Rose', role: 'Rental (Day Hire)', rating: 5, comment: 'Coimbatore temple visits full day super. Gentlest driver ever.' },
  { id: '25', name: 'Dinesh M', role: 'City to City', rating: 4, comment: 'CBE to Bengaluru drive safe. Konjam expensive but worth it.' },
  { id: '26', name: 'Keerthi S', role: 'Airport Transfer', rating: 5, comment: 'Cab punctual. Call panna thevayilla — already waiting. Impressed.' },
  { id: '27', name: 'Murugan', role: 'One-Way Outstation', rating: 5, comment: 'Tirupur drop on time. AC adjustable and pleasant.' },
  { id: '28', name: 'Yamini K', role: 'Outstation', rating: 4, comment: 'Yercaud-la climate nala irundhudhu. Trip memory ah pochu.' },
  { id: '29', name: 'Naren J', role: 'Rental (Day Hire)', rating: 5, comment: 'Whole day family outing. Kids kooda happy and relaxed.' },
  // Fixed: removed 'website' property which does not exist in type 'Testimonial' on line 140
  { id: '30', name: 'Praveena', role: 'City to City', rating: 5, comment: 'CBE to Trichy highway drive steady. Breaks proper intervals.' },
  { id: '31', name: 'Suresh B', role: 'Airport Transfer', rating: 5, comment: 'Flight arrival change, still adjust pannanga. Customer care super!' },
  { id: '32', name: 'Lavanya V', role: 'Outstation Drop', rating: 4, comment: 'Guruvayur temple-la drop pannanga. Parking ellam handle pannaaru. Very helpful.' },
  { id: '33', name: 'Abdul Rahman', role: 'Outstation', rating: 5, comment: 'OOTR roads twisty irundhaalum handle pannaaru. Safety first.' },
  { id: '34', name: 'Reshma', role: 'Rental (Day Hire)', rating: 4, comment: 'Car smell fresh. Perfect for outstation weddings.' },
  { id: '35', name: 'Barath', role: 'City to City', rating: 5, comment: 'CBE to Salem drop. Speed & safety balance great.' },
  { id: '36', name: 'Nisha M', role: 'Airport Transfer', rating: 5, comment: 'Ladies solo travel kooda safe feel pannalaam. Highly recommended.' },
  { id: '37', name: 'Ragavan', role: 'One-Way Outstation', rating: 4, comment: 'Dharmapuri trip. Driver wait panni return drop pannaaru.' },
  { id: '38', name: 'Gayathri', role: 'Outstation', rating: 5, comment: 'Kodaikanal sunset miss aagama route speed adjust pannaaru. Mind-blowing service.' },
  { id: '39', name: 'Vijay K', role: 'Rental (Day Hire)', rating: 5, comment: 'Corporate clients meeting full day. Premium service.' },
  { id: '40', name: 'Sharanya', role: 'City to City', rating: 4, comment: 'CBE to Pondicherry ride romantic break trip. Nice atmosphere.' },
  { id: '41', name: 'Rithvik S', role: 'Airport Transfer', rating: 5, comment: 'Flight delay irundhaalum extra waiting charges minimal-a irundhudhu.' },
  { id: '42', name: 'Manimegalai', role: 'Outstation Trip', rating: 5, comment: 'Cab interior spotless. Ride smooth to Kochi without jerks.' },
  { id: '43', name: 'Ashwin Vel', role: 'Outstation', rating: 4, comment: 'Palani darshan trip awesome. Spiritual journey smooth.' },
  { id: '44', name: 'Swetha', role: 'Rental (Day Hire)', rating: 5, comment: 'Family tour full fun. Driver smiling & patient always.' },
  { id: '45', name: 'John Peter', role: 'City to City', rating: 4, comment: 'CBE to Vellore hospital travel. Driver very supportive.' },
  { id: '46', name: 'Rithanya', role: 'Airport Transfer', rating: 5, comment: 'Luggage heavy irundha kooda help pannanga. Nice behaviour.' },
  { id: '47', name: 'Sanjana', role: 'One-Way Outstation', rating: 5, comment: 'Long distance rides-ku reliable option. Fair meters & fixed rate.' },
  { id: '48', name: 'Karthick C', role: 'Outstation', rating: 5, comment: 'Wayanad trip full entertainment. Driver playlists perfect!' },
  { id: '49', name: 'Bhuvana', role: 'Rental (Day Hire)', rating: 4, comment: 'Outstation shoot locations-lam take pannanga. Stylish car.' },
  { id: '50', name: 'Sudeep', role: 'City to City', rating: 5, comment: 'CBE to Hyderabad long ride smooth. Night driving fantastic & safe.' },
  { id: '51', name: 'Suriya Raj', role: 'Airport Transfer', rating: 5, comment: 'காலை 4 மணிக்கே நேரம் தவறாமல் வந்தார்கள். பாதுகாப்பாக விமான நிலையத்துக்கு கொண்டு சென்றார்கள். மிக நன்றி.' },
  { id: '52', name: 'Gayathri Devi', role: 'Outstation Trip', rating: 5, comment: 'கார் சுத்தமாகவும் நன்றாக பராமரித்தும் இருந்தது. நீண்ட தூர பயணம் செய்ய மிகவும் வசதியாக இருந்தது.' },
  { id: '53', name: 'Prakash', role: 'Outstation', rating: 4, comment: 'ஊட்டி பயணம் முழுவதும் பாதுகாப்பாக ஓட்டி சென்றார். குடும்பத்துடன் அமைதியாக பயணம் செய்தோம்.' },
  { id: '54', name: 'Malarvizhi', role: 'Rental (Day Hire)', rating: 5, comment: 'ஒரு நாள் முழுவதும் கோயில் தரிசனங்களுக்கு அழைத்துச் சென்றார்கள். பொறுமையாக காத்திருந்தார்கள். சேவை சிறந்தது.' },
  { id: '55', name: 'Aravindh', role: 'City to City', rating: 5, comment: 'கோயம்புத்தூர் முதல் திருச்சி வரை தடுமாறாமல், சீராக ஓட்டினார். மூத்தவர்களுக்கு மிகவும் வசதியாக இருந்தது.' },
  { id: '56', name: 'Saranya', role: 'Airport Transfer', rating: 4, comment: 'பயணச்சுமைகள் எடுத்து உதவினார். நடத்தை மிகவும் நன்றாக இருந்தது.' },
  { id: '57', name: 'Ramesh Kumar', role: 'One-Way Outstation', rating: 5, comment: 'வெளியூர் செல்ல மிகவும் குறைந்த நேரத்தில் அழைத்துச் சென்றார். விலை நேர்மையாக இருந்தது.' },
  { id: '58', name: 'Indumathi', role: 'Outstation', rating: 5, comment: 'முன்னூர் பயணம் மிக அற்புதமாக இருந்தது. வழிகளையும் இடங்களையும் நன்றாக அறிந்திருந்தார்.' },
  { id: '59', name: 'Sathya Narayanan', role: 'Rental (Day Hire)', rating: 4, comment: 'கார் உள்மனம் புதிது போல இருந்தது. பயணமெங்கும் சோர்வு ஏதுமில்லை.' },
  { id: '60', name: 'City to City', role: 'Outstation', rating: 5, comment: 'கோயம்புத்தூர் முதல் பெங்களூரு வரை இரவு பயணம் செய்யும் போது மிகவும் பாதுகாப்பாக இருந்தது.' },
  { id: '61', name: 'Dhanush', role: 'Airport Transfer', rating: 5, comment: 'விமானம் தாமதமானாலும் கூட கூடுதல் கட்டணம் குறைவாக இருந்தது. நேர்மையான சேவை.' },
  { id: '62', name: 'Revathi', role: 'One-Way Outstation', rating: 4, comment: 'பழனிக்கு அழைத்துச் சென்று காத்திருந்து திரும்பவும் கொண்டு வந்தார். மனதில் நிற்கும் சேவை.' },
  { id: '63', name: 'Hariharan', role: 'Outstation', rating: 5, comment: 'சாலை சரிவுகளிலும், மலைப் பாதைகளிலும் மிகவும் கவனமாக ஓட்டினார். நம் குடும்பம் மிகவும் மகிழ்ச்சி அடைந்தது.' },
  { id: '64', name: 'Aishwarya', role: 'Rental (Day Hire)', rating: 5, comment: 'ஒரு நாள் முழுவதும் சுற்றுலா போகும்போது எங்களின் தேவையை புரிந்துகொண்டு அமைதியாக சேவை செய்தார்கள்.' },
  { id: '65', name: 'Sundar', role: 'City to City', rating: 5, comment: 'கோயம்புத்தூர் முதல் மதுரை வரை பயணம் அமைதியாகவும் சுகமாகவும் இருந்தது. மீண்டும் இதே சேவையை தேர்வு செய்வோம்.' }
];

